---
apiVersion: install.tetrate.io/v1alpha1
kind: ControlPlane
metadata:
  name: controlplane
  namespace: istio-system
spec:
  hub: $TSB_INSTALL_REPO_URL
  managementPlane:
    host: $TSB_API_ENDPOINT
    port: 8443
    clusterName: app-cluster1
    selfSigned: true
  telemetryStore:
    elastic:
      host: $TSB_API_ENDPOINT
      port: 8443
      version: 7
      selfSigned: true
  components:
    internalCertProvider:
      certManager:
        managed: INTERNAL
    xcp:
      centralAuthMode: JWT
      # enableHttpMeshInternalIdentityPropagation: true
      kubeSpec:
        overlays:
        - apiVersion: install.xcp.tetrate.io/v1alpha1
          kind: EdgeXcp
          name: edge-xcp
          patches:
          - path: spec.centralAuthJwt.centralSni
            value: "central.xcp.tetrate.io"
          - path: spec.components.edgeServer.kubeSpec.deployment.env[-1]
            value:
              name: ENABLE_ENHANCED_EAST_WEST_ROUTING
              value: "true"
