---
apiVersion: api.tsb.tetrate.io/v2
kind: Tenant
metadata:
  organization: tetrate
  name: prod-abc
spec:
  displayName: ProductionABC
---
apiVersion: api.tsb.tetrate.io/v2
kind: Tenant
metadata:
  organization: tetrate
  name: prod-def
spec:
  displayName: ProductionDEF
---
apiVersion: api.tsb.tetrate.io/v2
kind: Tenant
metadata:
  organization: tetrate
  name: prod-ghi
spec:
  displayName: ProductionGHI
