---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-app-a
  namespace: ns-a
  labels:
    app: app-a
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-app-b
  namespace: ns-b
  labels:
    app: app-b
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-app-g
  namespace: ns-g
  labels:
    app: app-g
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-app-h
  namespace: ns-h
  labels:
    app: app-h
