---
apiVersion: v1
kind: Service
metadata:
  name: app-a
  namespace: ns-a
  labels:
    app: app-a
    service: app-a
spec:
  ports:
    - port: 80
      targetPort: 8000
      name: http
    - port: 3000
      targetPort: 3000
      name: tcp
  selector:
    app: app-a
---
apiVersion: v1
kind: Service
metadata:
  name: app-b
  namespace: ns-b
  labels:
    app: app-b
    service: app-b
spec:
  ports:
    - port: 80
      targetPort: 8000
      name: http
    - port: 3000
      targetPort: 3000
      name: tcp
  selector:
    app: app-b
---
apiVersion: v1
kind: Service
metadata:
  name: app-g
  namespace: ns-g
  labels:
    app: app-g
    service: app-g
spec:
  ports:
    - port: 80
      targetPort: 8000
      name: http
    - port: 3000
      targetPort: 3000
      name: tcp
  selector:
    app: app-g

---
apiVersion: v1
kind: Service
metadata:
  name: app-h
  namespace: ns-h
  labels:
    app: app-h
    service: app-h
spec:
  ports:
    - port: 80
      targetPort: 8000
      name: http
    - port: 3000
      targetPort: 3000
      name: tcp
  selector:
    app: app-h
