---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-app-a
  namespace: ns-a
  labels:
    app: app-a
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-app-b
  namespace: ns-b
  labels:
    app: app-b
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-app-c
  namespace: ns-c
  labels:
    app: app-c
