---
apiVersion: api.tsb.tetrate.io/v2
kind: WorkspaceSetting
metadata:
  organization: tetrate
  tenant: prod
  workspace: app-a-ws
  name: app-a-ws-setting
spec:
  defaultTrafficSetting:
    reachability:
      hosts:
      - ns-b/*
      mode: CUSTOM
---
apiVersion: api.tsb.tetrate.io/v2
kind: WorkspaceSetting
metadata:
  organization: tetrate
  tenant: prod
  workspace: app-b-ws
  name: app-b-ws-setting
spec:
  defaultTrafficSetting:
    reachability:
      hosts:
      - ns-c/*
      mode: CUSTOM
---
apiVersion: api.tsb.tetrate.io/v2
kind: WorkspaceSetting
metadata:
  organization: tetrate
  tenant: prod
  workspace: app-c-ws
  name: app-c-ws-setting
spec:
  defaultTrafficSetting:
    reachability:
      hosts:
      - ./*
      mode: CUSTOM
