---
apiVersion: gateway.tsb.tetrate.io/v2
kind: IngressGateway
metadata:
  annotations:
    tsb.tetrate.io/organization: tetrate
    tsb.tetrate.io/tenant: prod
    tsb.tetrate.io/workspace: gw-abc-ws
    tsb.tetrate.io/gatewayGroup: gw-abc-group
  name: gw-ingress-abc
spec:
  displayName: AppABC_IngressGW
  workloadSelector:
    namespace: gateway-abc
    labels:
      app: gw-ingress-abc
  http:
  - name: abc
    hostname: abc.demo.tetrate.io
    port: 80
    routing:
      rules:
      - route:
          host: ns-a/app-a.ns-a.svc.cluster.local
          port: 80
