---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-app-c
  namespace: ns-c
  labels:
    app: app-c
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-app-d
  namespace: ns-d
  labels:
    app: app-d
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-app-e
  namespace: ns-e
  labels:
    app: app-e
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-app-f
  namespace: ns-f
  labels:
    app: app-f
