---
apiVersion: v1
kind: Namespace
metadata:
  name: gateway-t1-efgh
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: gateway-transit2-c
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: gateway-transit2-g
  labels:
    istio-injection: enabled
