---
apiVersion: api.tsb.tetrate.io/v2
kind: OrganizationSetting
metadata:
  name: tetrate-settings
  organization: tetrate
spec:
  networkSettings:
    networkReachability:
      tier1-1: tier2-1,tier1-2
      tier1-2: tier2-2,tier1-1
      tier2-1: tier1-1
      tier2-2: tier1-2
