---
apiVersion: api.tsb.tetrate.io/v2
kind: Cluster
metadata:
  organization: tetrate
  name: mgmt
spec:
  locality:
    region: region0
  tier1Cluster: true
  tokenTtl: 31536000s
  network: mgmt
---
apiVersion: api.tsb.tetrate.io/v2
kind: Cluster
metadata:
  organization: tetrate
  name: app1
spec:
  locality:
    region: region1
  tier1Cluster: false
  tokenTtl: 31536000s
  network: apps1
---
apiVersion: api.tsb.tetrate.io/v2
kind: Cluster
metadata:
  organization: tetrate
  name: transit1
spec:
  locality:
    region: region1
  tier1Cluster: true
  tokenTtl: 31536000s
  network: transit1
---
apiVersion: api.tsb.tetrate.io/v2
kind: Cluster
metadata:
  organization: tetrate
  name: transit2
spec:
  locality:
    region: region2
  tier1Cluster: true
  tokenTtl: 31536000s
  network: transit2
---
apiVersion: api.tsb.tetrate.io/v2
kind: Cluster
metadata:
  organization: tetrate
  name: app2
spec:
  locality:
    region: region2
  tier1Cluster: false
  tokenTtl: 31536000s
  network: apps2
