---
apiVersion: api.tsb.tetrate.io/v2
kind: Cluster
metadata:
  organization: tetrate
  name: demo-cluster
spec:
  locality:
    region: region1
  tier1Cluster: false
  tokenTtl: 31536000s
  network: tier1
