---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-app1
  namespace: app1
  labels:
    app: app1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-app2
  namespace: app2
  labels:
    app: app2
