apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tsb
commonLabels:
  app: openldap-ui
images:
  - name: openldap-ui
    newTag: "v1.10"
    newName: wheelybird/ldap-user-manager
resources:
  - resources/deployment.yaml
  - resources/loadbalancer.yaml
