---
apiVersion: api.tsb.tetrate.io/v2
kind: WorkspaceSetting
metadata:
  organization: tetrate
  tenant: prod
  workspace: app-a-ws
  name: app-a-ws-setting
spec:
  defaultEastWestGatewaySettings:
    - workloadSelector:
        namespace: gateway-abc
        labels:
          app: gw-eastwest-abc
      exposedServices:
      - serviceLabels:
          app: app-a
          service: app-a
  defaultTrafficSetting:
    reachability:
      hosts:
      - ns-b/*
      mode: CUSTOM
---
apiVersion: api.tsb.tetrate.io/v2
kind: WorkspaceSetting
metadata:
  organization: tetrate
  tenant: prod
  workspace: app-b-ws
  name: app-b-ws-setting
spec:
  defaultEastWestGatewaySettings:
    - workloadSelector:
        namespace: gateway-abc
        labels:
          app: gw-eastwest-abc
      exposedServices:
      - serviceLabels:
          app: app-b
          service: app-b
  defaultTrafficSetting:
    reachability:
      hosts:
      - ns-c/*
      mode: CUSTOM
---
apiVersion: api.tsb.tetrate.io/v2
kind: WorkspaceSetting
metadata:
  organization: tetrate
  tenant: prod
  workspace: app-c-ws
  name: app-c-ws-setting
spec:
  defaultEastWestGatewaySettings:
    - workloadSelector:
        namespace: gateway-abc
        labels:
          app: gw-eastwest-abc
      exposedServices:
      - serviceLabels:
          app: app-c
          service: app-c
  defaultTrafficSetting:
    reachability:
      hosts:
      - ./*
      mode: CUSTOM
