---
apiVersion: gateway.tsb.tetrate.io/v2
kind: Tier1Gateway
metadata:
  organization: tetrate
  tenant: prod
  workspace: gw-tier1-ws
  group: gw-tier1-group
  name: gw-tier1-abc
spec:
  displayName: AppABC_Tier1GW
  workloadSelector:
    namespace: gateway-tier1
    labels:
      app: gw-tier1-abc
  externalServers:
  - name: abc-https
    hostname: abc.demo.tetrate.io
    port: 443
    tls:
      mode: SIMPLE
      secretName: app-abc-cert
    clusters:
    - name: active
    - name: standby
