---
apiVersion: gateway.tsb.tetrate.io/v2
kind: IngressGateway
metadata:
  organization: tetrate
  tenant: prod
  workspace: gw-abc-ws
  group: gw-abc-group
  name: gw-ingress-abc
spec:
  displayName: AppABC_IngressGW
  workloadSelector:
    namespace: gateway-abc
    labels:
      app: gw-ingress-abc
  http:
  - name: abc
    hostname: abc.demo.tetrate.io
    port: 443
    tls:
      mode: SIMPLE
      secretName: app-abc-cert
    routing:
      rules:
      - route:
          host: ns-a/app-a.ns-a.svc.cluster.local
          port: 80
