---
apiVersion: security.tsb.tetrate.io/v2
kind: SecuritySetting
metadata:
  organization: tetrate
  tenant: prod
  workspace: app-a-ws
  group: app-a-security-group
  name: ingress-to-a
spec:
  authenticationSettings:
    trafficMode: REQUIRED
  authorization:
    mode: RULES
    rules:
      allow:
       - from:
           fqn: organizations/tetrate/tenants/prod/workspaces/gw-abc-ws
         to:
           fqn: organizations/tetrate/tenants/prod/workspaces/app-a-ws/securitygroups/app-a-security-group
---
apiVersion: security.tsb.tetrate.io/v2
kind: SecuritySetting
metadata:
  organization: tetrate
  tenant: prod
  workspace: app-b-ws
  group: app-b-security-group
  name: a-to-b
spec:
  authenticationSettings:
    trafficMode: REQUIRED
  authorization:
    mode: RULES
    rules:
      allow:
       - from:
           fqn: organizations/tetrate/tenants/prod/workspaces/app-a-ws
         to:
           fqn: organizations/tetrate/tenants/prod/workspaces/app-b-ws/securitygroups/app-b-security-group
---
apiVersion: security.tsb.tetrate.io/v2
kind: SecuritySetting
metadata:
  organization: tetrate
  tenant: prod
  workspace: app-c-ws
  group: app-c-security-group
  name: b-to-c
spec:
  authenticationSettings:
    trafficMode: REQUIRED
  authorization:
    mode: RULES
    rules:
      allow:
       - from:
           fqn: organizations/tetrate/tenants/prod/workspaces/app-b-ws
         to:
           fqn: organizations/tetrate/tenants/prod/workspaces/app-c-ws/securitygroups/app-c-security-group
